networks:
  default:
    driver: bridge
    attachable: true
    enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  site:
    image: node:16-alpine3.15
    container_name: gp-site-dev
    hostname: gp-site
    expose: [3000]
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ${SITE_PATH}
        target: ${SITE_PATH}
    working_dir: ${SITE_PATH}
    command: yarn s
