volumes:
  nginx-vol:
    name: gp-nginx-vol
    external: true

services:
  gp-site-serv:
    image: node:16-alpine3.15
    container_name: gp-site-dev
    expose: [3000]
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: /home/romaro/gp
        target: /home/romaro/gp
    working_dir: /home/romaro/gp
    command: yarn s
  gp-nginx-serv:
    build: ./docker/nginx
    container_name: gp-nginx
    expose: [80, 443]
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: volume
        source: nginx-vol
        target: /var/log/nginx
      - type: bind
        source: /home/romaro/gp/files
        target: /etc/static
    depends_on:
      - gp-site-serv