volumes:
  nginx-vol:
    name: gp-nginx-vol
    external: true

services:
  gp-site-serv:
    image: node:16-alpine3.15
    container_name: gp-site-dev
    expose: [5000]
    ports:
      - 3000:5000
    volumes:
      - type: bind
        source: ${SITE_PATH}
        target: ${SITE_PATH}
    working_dir: ${SITE_PATH}
    command: yarn s
  gp-nginx-serv:
    build: ./docker/nginx
    container_name: gp-nginx
    expose: [80, 443]
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: volume
        source: nginx-vol
        target: /var/log/nginx
      - type: bind
        source: ${NGINX_CONFIG_SRC}
        target: /etc/static
    depends_on:
      - gp-site-serv